// Controlled vocabularies for BD01A.
//
// Extracted verbatim from the legacy config.js and BD01A.html on 25 August 2026.
// These values feed the ProposalID, so they MUST match the legacy set exactly.
// Do not tidy, reorder or "correct" them. When these move to the Decoder master
// at B12, this file is replaced by a fetch, not edited.

export const vocab = {
  pgCompany: ["PE", "PS", "PR", "PW"],

  stUt: [
    "AP",
    "AR",
    "AS",
    "BR",
    "CG",
    "GA",
    "GJ",
    "HR",
    "HP",
    "JH",
    "KA",
    "KL",
    "MP",
    "MH",
    "MN",
    "ML",
    "MZ",
    "NL",
    "OR",
    "PB",
    "RJ",
    "SK",
    "TN",
    "TG",
    "TR",
    "UP",
    "UT",
    "WB",
    "AN",
    "CH",
    "DN",
    "DD",
    "DL",
    "JK",
    "LA",
    "LD",
    "PY",
  ],

  workType: [
    "AAM",
    "ADR",
    "AIR",
    "CCR",
    "CEO",
    "CFP",
    "CRE",
    "CRZ",
    "CTE",
    "CTO",
    "DUA",
    "EAM",
    "EAS",
    "EBD",
    "ECC",
    "ECE",
    "ECO",
    "ECP",
    "ECR",
    "ECV",
    "EEO",
    "EFA",
    "EFC",
    "EGA",
    "EIA",
    "EMP",
    "ENA",
    "ENC",
    "ENS",
    "EPH",
    "EPO",
    "EPR",
    "ESD",
    "ESI",
    "FCA",
    "FEO",
    "FOR",
    "GWC",
    "HAZ",
    "IMP",
    "LCA",
    "LCS",
    "LIM",
    "MON",
    "MPA",
    "NCC",
    "NEC",
    "NOA",
    "PLA",
    "QRA",
    "SFA",
    "SIL",
    "SOA",
    "STK",
    "TAM",
    "TEC",
    "TOR",
    "WAT",
    "WLC",
    "WPM",
    "WTA",
    "EEX",
    "SEC",
    "other",
  ],

  sector: [
    "1A",
    "1B",
    "1D",
    "2A",
    "2B",
    "3A",
    "3B",
    "4A",
    "4B",
    "4C",
    "4D",
    "4F",
    "5A",
    "5B",
    "5C",
    "5D",
    "5E",
    "5F",
    "5G",
    "5H",
    "5J",
    "6A",
    "6B",
    "7A",
    "7B",
    "7C",
    "7D",
    "7DA",
    "7E",
    "7F",
    "7G",
    "7H",
    "7I",
    "8A",
    "8B",
    "71",
    "72",
    "73",
    "74",
    "75",
    "76",
    "77",
    "78",
    "79",
    "80",
    "81",
    "82",
    "N/A",
    "others",
  ],

  specs: [
    "NA0",
    "GA0",
    "GB1",
    "GB2",
    "GTA",
    "GEA",
    "GEX",
    "GTR",
    "GPL",
    "BA0",
    "BB1",
    "BB2",
    "BTA",
    "BEA",
    "BTR",
    "BPL",
    "CG1",
    "CG2",
  ],

  customerClass: [
    { value: "new", label: "New Customer" },
    { value: "existing", label: "Existing Customer" },
  ],

  isRepeatCustomer: [
    { value: "yes", label: "Yes" },
    { value: "no", label: "No" },
  ],

  leadSource: [
    { value: "pb", label: "Mr. Praveen Bhargava" },
    { value: "rb", label: "Mrs. Rachna Bhargava" },
    { value: "nb", label: "Dr. Nipun Bhargava" },
    { value: "rd", label: "Mrs. Rachna Dogra" },
    { value: "gmk", label: "Mr. Muthukumaran Ganpathi Narayanan" },
    { value: "ag", label: "Mrs. Aarti Gupta" },
    { value: "others", label: "Others" },
  ],
};

/** Financial years offered, current and next. FY 2026-27 is entered as 2027. */
export function financialYears() {
  const now = new Date();
  const startYear =
    now.getMonth() >= 3 ? now.getFullYear() : now.getFullYear() - 1;
  return [String(startYear + 1), String(startYear + 2)];
}
